logging:
  path: log/
server:
    port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.227.132:3306/test?useUnicode=true&characterEncoding=utf-88&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
    typeAliasesPackage: com.bfec.transfer
    mapperLocations: classpath:/sqlxml/*.xml
    configLocation: classpath:/mybatis-config.xml

