server:
    port: 8082
dbs:
  - name: dpt_e-commerce
    jdbc-url: jdbc:mysql://192.168.2.110:3301/dpt_e-commerce?useUnicode=true&characterEncoding=utf-88&serverTimezone=Hongkong&useSSL=false
    username: dpt_dev
    password: dev20161111
    driverClassName: com.mysql.cj.jdbc.Driver
  - name: sso
    jdbc-url: jdbc:mysql://192.168.2.110:3301/sso?useUnicode=true&characterEncoding=utf-88&serverTimezone=Hongkong&useSSL=false
    username: dpt_dev
    password: dev20161111
    driverClassName: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #      最小空闲链接数
      minimumIdle: 2
      #      最大链接数
      maximumPoolSize: 10
      #      最大生命周期
      maxLifetime: 180000
      #      最长闲置时间
      idleTimeout: 60000
      #      等待连接池的最大毫秒数
      connectionTimeout: 20000
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bfec.transfer
logging:
  config: classpath:logback-spring.xml

