logging:
  path: log/
server:
    port: 8082
#    contextPath: /group
# DATASOURCE
# 联合数据
jdbc_league_data:
    DriverClass: com.mysql.jdbc.Driver
    JdbcUrl: jdbc:mysql://192.168.2.110:3301/league_data?useunicode=true&characterencoding=utf8&autoreconnect=true&rewritebatchedstatements=true&zerodatetimebehavior=converttonull
    User: dpt_dev
    Password: dev20161111
mybatis:
    typeAliasesPackage: com.bfec.transfer
    mapperLocations: classpath:/sqlxml/*.xml
    configLocation: classpath:/mybatis-config.xml

