server:
  port: 8082
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://192.168.227.135:3306/dpt_e-commerce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
        slaves:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://192.168.227.135:3306/sso?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#spring:
#  datasource:
#    dynamic:
#      primary: master
#      datasource:
#        master:
#          type: com.zaxxer.hikari.HikariDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          username: dpt_dev
#          password: dev20161111
#          url: jdbc:mysql://192.168.2.110:3301/dpt_e-commerce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#        slaves:
#          type: com.zaxxer.hikari.HikariDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          username: dpt_dev
#          password: dev20161111
#          url: jdbc:mysql://192.168.2.110:3301/sso?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bfec.transfer
logging:
  config: classpath:logback-spring.xml